accessID: ZhLe93tj7c32P5YwxaJg
accessKey: 'z2++%]f8{523J3UuEfr7J[f7V8^M_^Zp(B7]K88E'
account: lmsrikarachanta
clusterName: eks-se-bootcamp
logLevel: info
deleteDevices: true
disableAlerting: false
enableRBAC: true
clusterGroupID: 1
resourceGroupID: 1
etcdDiscoveryToken: ''
imageRepository: logicmonitor/argus
imageTag: v6
imagePullPolicy: Always
proxyURL: ''
proxyUser: ''
proxyPass: ''
nodeSelector: {}
affinity: {}
priorityClassName: ''
tolerations: []
labels: {}
annotations: {}
ignore_ssl: false
registerGenericFilter: false
app_intervals:
  periodic_sync_interval: 30m
  periodic_delete_interval: 10m
  cache_sync_interval: 1h
device_group_props:
  cluster:
    - name: lmlogs.k8sevent.enable
      value: 'true'
    - name: kubernetes.resourcedeleteafterduration
      value: P1DT0H0M0S
      override: false
  pods:
    - name: lmlogs.k8spodlog.enable
      value: 'true'
  services: []
  deployments: []
  nodes: []
  etcd: []
  hpas: []
filters:
  pod: ''
  service: ''
  node: ''
  deployment: ''
  hpa: ''
  daemonset: ''
  replicaset: ''
  statefulset: ''
  persistentvolume: ''
openmetrics:
  port: 2112
collector:
  replicas: '1'
  size: nano
  imageRepository: logicmonitor/collector
  imageTag: latest
  imagePullPolicy: Always
  secretName: collector
  groupID: -1
  escalationChainID: '0'
  collectorVersion: 0
  useEA: false
  proxyURL: ''
  proxyUser: ''
  proxyPass: ''
  annotations: {}
  labels: {}
  statefulsetspec:
    template:
      spec:
        nodeSelector: {}
        tolerations: []
        priorityClassName: ''
disableResourceMonitoring: null
disableResourceAlerting: null
replicas: 1
kube-state-metrics:
  enabled: true
  replicas: 1
  collectors:
    - daemonsets
    - replicasets
    - statefulsets
    - persistentvolumes
