accessID: ZhLe93tj7c32P5YwxaJg
accessKey: 'z2++%]f8{523J3UuEfr7J[f7V8^M_^Zp(B7]K88E'
account: lmsrikarachanta
debug: true
enableRBAC: true
etcdDiscoveryToken: ''
imageRepository: logicmonitor/collectorset-controller
imageTag: v2
imagePullPolicy: Always
proxyURL: ''
proxyUser: ''
proxyPass: ''
nodeSelector: {}
affinity: {}
priorityClassName: ''
tolerations: []
labels: {}
annotations: {}
ignore_ssl: false
