apiVersion: apps/v1
kind: Deployment
metadata:
  name: 
    sbdemo-apserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sbdemo-apserver
  template:
    metadata:
      labels:
        app: sbdemo-apserver
      annotations:
        sidecar.opentelemetry.io/inject: "true"
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:     
      containers:
      - name: apserver
        image: aasrikar/springdemoapp-auto-java-otel:latest
        imagePullPolicy: Always
        #command: ["java", "-javaagent:/opt/javaagent/opentelemetry-javaagent.jar", "-Dotel.traces.exporter=otlp", "-Dotel.exporter.otlp.endpoint=http://34.71.182.228:4317", "-jar", "/app/springdemo.jar"]
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "prd"
          - name: DB_URL
            value: "jdbc:postgresql://sbdemo-postgres-service:5432/demodb?user=postgres&password=postgres"
          - name: PIC_DIR
            value: "/opt"
          - name: REDIS_HOST
            value: "sbdemo-redis-service"
          - name: REDIS_PORT
            value: "6379"

      
